services:
  website:
    container_name: portfolio-website
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "${WEBSITE_PROD_PORT:-4173}:80"
    restart: unless-stopped
